universe = vanilla
Executable = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2023BPix/Job_test_1.sh
should_transfer_files = YES
Transfer_Input_Files = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2023BPix/Job_test_1.sh, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_vbf/bin/vbfhmm_config_run3_vbf_uncertainty_top_2023BPix, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_vbf/libCROWNLIB.so
Proxy_path = /afs/cern.ch/user/j/jiahua/proxy/x509up_u139833
output_path = /eos/user/j/jiahua/MC_2023BPix_inc/MC_2023BPix_vbf/GluGluHto2Mu_M-125_powheg_23BPix
arguments = $(Proxy_path) $(output_path) $(input_name) $(ClusterID) $(ProcId)
Output = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2023BPix/Jobs/GluGluHto2Mu_M-125_powheg_23BPix_$(ClusterId)_$(ProcId).out
Error = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2023BPix/Jobs/GluGluHto2Mu_M-125_powheg_23BPix_$(ClusterId)_$(ProcId).err
Log = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2023BPix/Jobs/GluGluHto2Mu_M-125_powheg_23BPix_$(ClusterId)_$(ProcId).log
request_cpus = 1
+JobFlavour = "workday"
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23BPixNanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_postBPix_v6-v2/2820000/0b4e3463-ff85-4a8d-9afd-ea11469ddcff.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23BPixNanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_postBPix_v6-v2/2820000/2025b0db-a786-4932-a937-97f11836f3e7.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23BPixNanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_postBPix_v6-v2/2820000/32b27522-a3ac-4f36-9c3f-072a7fa4f6c5.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23BPixNanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_postBPix_v6-v2/2820000/959579bd-14ac-47eb-ab6e-a2519938a8d0.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23BPixNanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_postBPix_v6-v2/2820000/c270bfcc-7036-4fc6-8633-9d9307c56aa9.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23BPixNanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_postBPix_v6-v2/2820000/404424d7-834b-4447-945d-57880a8a5a17.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23BPixNanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_postBPix_v6-v2/2820000/1bdbdc3c-3046-4c13-a1c0-1810be13667c.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23BPixNanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_postBPix_v6-v2/2820000/beec7c56-d7bb-4a27-9aad-cc8351b6c11b.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23BPixNanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_postBPix_v6-v2/2820000/82414a78-64e4-4b61-956d-6ab271360950.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23BPixNanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_postBPix_v6-v2/2820000/8074908a-0add-4d6d-b997-d74318e5e6e0.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23BPixNanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_postBPix_v6-v2/2820000/693961c0-6b07-4794-8f3b-28adc4e68734.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23BPixNanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_postBPix_v6-v2/2820000/9eaa8d4e-798a-4dec-9d70-4b5ed5df17f0.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23BPixNanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_postBPix_v6-v2/2820000/d6ff7b6c-7b3b-4ae4-9c45-c4bb53e628cc.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23BPixNanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_postBPix_v6-v2/2820000/991dce16-4ff4-40e1-9882-98ada44b0a73.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23BPixNanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_postBPix_v6-v2/2820000/a5cee73a-6020-403d-aa57-5bd47d38d4c2.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23BPixNanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_postBPix_v6-v2/2820000/005b95d9-0ea3-49a6-ab7e-a5f13bce5c82.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23BPixNanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_postBPix_v6-v2/2820000/1f81b8b0-a55c-4521-b86f-ad1bed9a9c61.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23BPixNanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_postBPix_v6-v2/2820000/f6db1b64-8331-47b3-9ec0-e2e3b595182b.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23BPixNanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_postBPix_v6-v2/2820000/78ef962f-9419-47c3-97e3-47599df669f6.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23BPixNanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_postBPix_v6-v2/2560000/efde6374-06e9-48cc-9824-86a1086e4324.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23BPixNanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_postBPix_v6-v2/1310000/319d1a62-84da-4064-9356-138958c242e8.root
Queue
