universe = vanilla
Executable = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2023BPix/Job_test_data.sh
should_transfer_files = YES
Transfer_Input_Files = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2023BPix/Job_test_data.sh, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_vbf_2023BPix/bin/vbfhmm_config_run3_vbf_HornVeto_2023BPix_data_2023BPix, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_vbf_2023BPix/libCROWNLIB.so
Proxy_path = /afs/cern.ch/user/j/jiahua/proxy/x509up_u139833
output_path = /eos/user/j/jiahua/MC_2023BPix_inc/MC_2023BPix_vbf/Muon0_Run2023D-24Jan2024_v2-v1
arguments = $(Proxy_path) $(output_path) $(input_name) $(ClusterID) $(ProcId)
Output = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2023BPix/Jobs/Muon0_Run2023D-24Jan2024_v2-v1_$(ClusterId)_$(ProcId).out
Error = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2023BPix/Jobs/Muon0_Run2023D-24Jan2024_v2-v1_$(ClusterId)_$(ProcId).err
Log = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2023BPix/Jobs/Muon0_Run2023D-24Jan2024_v2-v1_$(ClusterId)_$(ProcId).log
request_cpus = 1
+JobFlavour = "workday"
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v2-v1/2820000/5004d03d-76d7-47e3-9afc-62c3a66e8c84.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v2-v1/2820000/c717c139-7158-4818-9878-3e8c566295e1.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v2-v1/2820000/19386d41-110d-4756-b04f-577d4c0d6a79.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v2-v1/2820000/14461664-aebb-4a4a-bd86-3ad03bc3d8a4.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v2-v1/2820000/3fd2edec-3ec5-40a9-9106-0d3f9b118bfc.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v2-v1/2820000/db91cf74-77ef-4cbc-9bd3-2cf0f4225f7b.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v2-v1/2820000/840632af-4ee3-410d-bb96-2d486c2474df.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v2-v1/2820000/b01c272b-1afe-4151-87f9-1a56463a0f4b.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v2-v1/2820000/ba3d8bf5-e5c8-4b99-af24-ccbe0254ac4c.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v2-v1/2820000/bc15e86e-4678-4e60-be6c-ad723aff6b04.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v2-v1/2820000/146f29c9-26ff-4f1d-853f-06acb5c3b2c1.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v2-v1/2820000/f29eb305-f8ed-4217-ba91-a666ed14db1a.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v2-v1/2820000/e56926e3-a813-4023-a608-cc0b189e0f75.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v2-v1/2820000/1210167a-e6ea-423a-bff6-512819d2f544.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v2-v1/2820000/be0e61a1-7dda-4100-9325-31b703c8ac59.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v2-v1/2820000/c3cff39d-6ad1-41ac-bfbd-aafca2b92c93.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v2-v1/2820000/e7dad2fc-7362-496a-9b52-15f1f4423975.root
Queue
