universe = vanilla
Executable = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2023BPix/Job_test_data.sh
should_transfer_files = YES
Transfer_Input_Files = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2023BPix/Job_test_data.sh, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_vbf_2023BPix/bin/vbfhmm_config_run3_vbf_HornVeto_2023BPix_data_2023BPix, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_vbf_2023BPix/libCROWNLIB.so
Proxy_path = /afs/cern.ch/user/j/jiahua/proxy/x509up_u139833
output_path = /eos/user/j/jiahua/MC_2023BPix_inc/MC_2023BPix_vbf/Muon1_Run2023D-24Jan2024_v2-v1
arguments = $(Proxy_path) $(output_path) $(input_name) $(ClusterID) $(ProcId)
Output = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2023BPix/Jobs/Muon1_Run2023D-24Jan2024_v2-v1_$(ClusterId)_$(ProcId).out
Error = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2023BPix/Jobs/Muon1_Run2023D-24Jan2024_v2-v1_$(ClusterId)_$(ProcId).err
Log = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2023BPix/Jobs/Muon1_Run2023D-24Jan2024_v2-v1_$(ClusterId)_$(ProcId).log
request_cpus = 1
+JobFlavour = "workday"
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon1/NANOAOD/24Jan2024_v2-v1/30000/c4c0f6a5-cb63-4af6-90e4-a10826f0f931.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon1/NANOAOD/24Jan2024_v2-v1/30000/3b50297b-f59e-4e28-8bd2-88cfff07ff44.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon1/NANOAOD/24Jan2024_v2-v1/30000/6ebc0a50-be89-4885-8664-e9137806d48e.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon1/NANOAOD/24Jan2024_v2-v1/30000/90ed3eb3-0b4b-49a6-8080-c5173c7150ea.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon1/NANOAOD/24Jan2024_v2-v1/30000/d29bd41e-588e-4fab-8233-225b44b17961.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon1/NANOAOD/24Jan2024_v2-v1/30000/ab468d36-cb59-416d-8ebe-18cfdd4945be.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon1/NANOAOD/24Jan2024_v2-v1/30000/e3f5af7c-27f9-441a-bbec-3e0ee739bc36.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon1/NANOAOD/24Jan2024_v2-v1/30000/908bf135-5946-43dc-a430-bcab6e9801b8.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon1/NANOAOD/24Jan2024_v2-v1/30000/22fdbbc5-c77a-4fe0-afa1-f5bedf4dfa66.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon1/NANOAOD/24Jan2024_v2-v1/30000/2b86a722-0d85-4de0-9d8e-855cc6d48ff0.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon1/NANOAOD/24Jan2024_v2-v1/30000/c6ec3782-d5a7-403c-b9a0-0559a824b49f.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon1/NANOAOD/24Jan2024_v2-v1/30000/1f9d8f88-aec3-4d0f-83bf-4069c00c8b04.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon1/NANOAOD/24Jan2024_v2-v1/30000/1423f29e-0c8b-43d1-878e-09b8e40c6b38.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon1/NANOAOD/24Jan2024_v2-v1/30000/ed2f2574-88cc-4920-8917-60e5e602062e.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon1/NANOAOD/24Jan2024_v2-v1/30000/512fc89e-f74a-4086-ab3b-6256990892bb.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon1/NANOAOD/24Jan2024_v2-v1/30000/22fdf90b-c5ae-4098-a3d0-75651f5b4500.root
Queue
