universe = vanilla
Executable = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2023/Job_test_1.sh
should_transfer_files = YES
Transfer_Input_Files = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2023/Job_test_1.sh, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_2022/bin/vbfhmm_config_run3_vbf_test_top_2023, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_2022/libCROWNLIB.so
Proxy_path = /afs/cern.ch/user/j/jiahua/proxy/x509up_u139833
output_path = /eos/user/j/jiahua/MC_2023_inc/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7_23
arguments = $(Proxy_path) $(output_path) $(input_name) $(ClusterID) $(ProcId)
Output = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2023/Jobs/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7_23_$(ClusterId)_$(ProcId).out
Error = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2023/Jobs/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7_23_$(ClusterId)_$(ProcId).err
Log = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2023/Jobs/hello_$(ClusterId)_$(ProcId).log
request_cpus = 1
+JobFlavour = "workday"
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2023_realistic_v15-v2/130000/137de045-4509-46a7-a8b5-b3f522522eb2.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2023_realistic_v15-v2/130000/eeb72117-0556-44bb-9a96-a9b733c61a7e.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2023_realistic_v15-v2/130000/25c20a9b-11aa-4959-b30f-608c0734190b.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2023_realistic_v15-v2/130000/f6cce0d2-511e-4e21-b791-a82fbc61f142.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2023_realistic_v15-v2/130000/7c84c4e3-8759-4279-92ce-9aa66fbf3fc6.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2023_realistic_v15-v2/130000/39ff6696-2800-43b5-ad5e-8b38a8d40ea8.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2023_realistic_v15-v2/130000/60e0aaa5-808d-4dbc-ba37-838e0f98133f.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2023_realistic_v15-v2/130000/ae63295f-943e-4b9a-a239-56fd4be7044c.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2023_realistic_v15-v2/130000/1f727412-4410-4237-87df-be695ca66140.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2023_realistic_v15-v2/130000/7f7ba47b-ca50-4b97-b44e-923b4be87aa9.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2023_realistic_v15-v2/130000/69cfb703-9c64-47ac-98d8-9418ac091b03.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2023_realistic_v15-v2/130000/fa1f01bd-c60a-4647-a934-41afe5deb6ae.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2023_realistic_v15-v2/130000/eb6d5b7d-55cb-4dd3-8363-6ba1693ee561.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2023_realistic_v15-v2/130000/0044d55b-c8a2-48e7-b80c-0e161ddc0a0e.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2023_realistic_v15-v2/130000/c906c9d6-ea99-4dce-963d-36b4a09aeb42.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2023_realistic_v15-v2/130000/acdec95c-9d47-417f-a0e7-1aa95373653a.root
Queue
