universe = vanilla
Executable = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2023/Job_test_1.sh
should_transfer_files = YES
Transfer_Input_Files = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2023/Job_test_1.sh, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_2022/bin/vbfhmm_config_run3_vbf_test_top_2023, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_2022/libCROWNLIB.so
Proxy_path = /afs/cern.ch/user/j/jiahua/proxy/x509up_u139833
output_path = /eos/user/j/jiahua/MC_2023_inc/TWminusto2L2Nu_powheg_23
arguments = $(Proxy_path) $(output_path) $(input_name) $(ClusterID) $(ProcId)
Output = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2023/Jobs/TWminusto2L2Nu_powheg_23_$(ClusterId)_$(ProcId).out
Error = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2023/Jobs/TWminusto2L2Nu_powheg_23_$(ClusterId)_$(ProcId).err
Log = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2023/Jobs/TWminusto2L2Nu_powheg_23_$(ClusterId)_$(ProcId).log
request_cpus = 1
+JobFlavour = "workday"
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/cf279e86-6ff9-48ad-9584-2978f101e169.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/ce92eec8-8dad-4a28-86e4-4096c55c9c60.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/5d2428ee-d688-4680-9456-f1ba6c132e34.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/0b70a87c-ff0a-4711-9487-e1a6961d4693.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/e0e02029-eb4d-424c-a84a-03ca1d46ff0f.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/e9aec4fc-6cb3-47ac-953d-9a383aca074e.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/597cc9b0-afb5-463a-ae81-de989d7f998b.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/b2f83af7-8624-46c5-9a03-316d85230e97.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/d374bf90-6b1e-4b9c-ac08-0180272f60ab.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/48417a83-1450-4eb5-88ad-117f42935d31.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/0c98d01c-35e1-451a-8daf-813dc76c7495.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/578e44c2-c268-4eb4-a6bb-8ae4c53c7dea.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/7ebd4255-79d0-4f52-b43b-6d7e0de6e04f.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/043aab8e-de42-4ede-a46f-1916ea299ca1.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/182d76cf-f33d-49b3-b34c-f6fe6c0e62a9.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/1cc0e472-06bd-4483-a09d-27c3fc50dd66.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/0e3cdb95-5e3d-46e2-bdcb-b736c9abec6f.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/afd43f78-8ff6-4fde-a242-37dddfd96e3f.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/c66d8d3f-d63f-4d30-8d2a-11ddbd7e464e.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/2677e721-b64b-44a7-931f-4b42370f26d4.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/3bd5c49c-4e0c-468a-85b8-3809be9ee209.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/98c31c76-4afe-4d24-b533-2fc37ac641d8.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/994fdb6c-a478-45bc-86cf-b6399330ce4a.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/8635154f-c32d-42cd-85de-b24e0f553215.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/2cf2f4ad-71ce-4759-afc5-c2c032cf0d6d.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/3686d558-e532-4446-8992-1ec9fd18b461.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/2c06b6ed-e45c-4697-aa6f-7e6b54b4ba29.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/141b1bb2-1597-4668-a521-b82e1ebf6f92.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/bf5ab50e-4764-46ee-9d3b-5defa83cc73a.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/11392e82-0278-4a31-8370-9e0f4c93b0ee.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/6a5ed7f8-7270-4930-913d-7684561de1e1.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/de11afdf-856d-4d77-96e8-a107cec0fce3.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/fd77845e-c8b1-49c6-8c30-53be3eb2b7b6.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v14-v2/2560000/716f64db-d9aa-412b-b23a-201047097b4e.root
Queue
