universe = vanilla
Executable = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022EE/Job_test_1.sh
should_transfer_files = YES
Transfer_Input_Files = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022EE/Job_test_1.sh, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_2022EE/bin/vbfhmm_config_run3_vbf_HornVeto_top_2022EE, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_2022EE/libCROWNLIB.so
Proxy_path = /afs/cern.ch/user/j/jiahua/proxy/x509up_u139833
output_path = /eos/user/j/jiahua/MC_2022EE_inc/MC_2022EE_vbf/WplusH_Hto2Mu_WtoAll_M-125_powheg_22EE
arguments = $(Proxy_path) $(output_path) $(input_name) $(ClusterID) $(ProcId)
Output = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022EE/Jobs/WplusH_Hto2Mu_WtoAll_M-125_powheg_22EE_$(ClusterId)_$(ProcId).out
Error = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022EE/Jobs/WplusH_Hto2Mu_WtoAll_M-125_powheg_22EE_$(ClusterId)_$(ProcId).err
Log = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022EE/Jobs/WplusH_Hto2Mu_WtoAll_M-125_powheg_22EE_$(ClusterId)_$(ProcId).log
request_cpus = 1
+JobFlavour = "workday"
input_name = root://cms-xrd-global.cern.ch/Python path configuration:
Queue
input_name = root://cms-xrd-global.cern.ch/  PYTHONHOME = '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt'
Queue
input_name = root://cms-xrd-global.cern.ch/  PYTHONPATH = (not set)
Queue
input_name = root://cms-xrd-global.cern.ch/  program name = '/usr/bin/python3'
Queue
input_name = root://cms-xrd-global.cern.ch/  isolated = 0
Queue
input_name = root://cms-xrd-global.cern.ch/  environment = 1
Queue
input_name = root://cms-xrd-global.cern.ch/  user site = 1
Queue
input_name = root://cms-xrd-global.cern.ch/  import site = 1
Queue
input_name = root://cms-xrd-global.cern.ch/  sys._base_executable = '/usr/bin/python3'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.base_prefix = '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.base_exec_prefix = '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.platlibdir = 'lib64'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.executable = '/usr/bin/python3'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.prefix = '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.exec_prefix = '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.path = [
Queue
input_name = root://cms-xrd-global.cern.ch/    '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt/lib64/python39.zip',
Queue
input_name = root://cms-xrd-global.cern.ch/    '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt/lib64/python3.9',
Queue
input_name = root://cms-xrd-global.cern.ch/    '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt/lib64/python3.9/lib-dynload',
Queue
input_name = root://cms-xrd-global.cern.ch/  ]
Queue
input_name = root://cms-xrd-global.cern.ch/Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Queue
input_name = root://cms-xrd-global.cern.ch/Python runtime state: core initialized
Queue
input_name = root://cms-xrd-global.cern.ch/ModuleNotFoundError: No module named 'encodings'
Queue
input_name = root://cms-xrd-global.cern.ch/
Queue
input_name = root://cms-xrd-global.cern.ch/Current thread 0x00007f67071fb740 (most recent call first):
Queue
input_name = root://cms-xrd-global.cern.ch/<no Python frame>
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/2c306c16-6d41-4119-991d-e057651a6e81.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/932cd8d3-7577-43a8-82c7-7023436e30e9.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/b7f0beb7-6024-431b-84f2-07be423f9f58.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/b9575150-be3b-4b6f-9bb1-e0e4e5099667.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/b5ce7f55-190c-4a05-9308-4c748797c2eb.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/4fe6aa75-e48e-452d-9378-2d2d35083acc.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/ff024cf7-37b5-4073-bd3b-92a26b2b6723.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/a02712a4-16be-4cd5-b01e-399d736f4686.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/41f58c28-c8c7-476a-852c-0d906be21efb.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/f4735742-22d6-4c58-9816-6c535033227a.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/f07f659c-d1d5-426d-9891-156b33e3cec9.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/cca8d6c8-e6be-44e1-92c9-d4311f4b4152.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/420839fd-73e8-48f1-8fef-3836d827a4a7.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/e987843d-1529-42e8-b9e5-c0993cbc7d93.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/6e0a1185-3140-45ed-bdb9-14fc7e1e5a24.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/00f0c39f-83c9-4859-8fc1-934258468bb5.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/95297c79-ab96-4001-b055-87083aaf053c.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/49db20e8-18ca-4d61-9e83-de337b8886b4.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/138c94b1-af5d-44d6-98e2-fce0817445f8.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/feba8dc0-5e94-4037-bca0-dc8703d3fd55.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/0d92a104-5294-4dd8-b63b-cd4460ab9e07.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/10f68a3f-3542-48cd-aa04-ae078dd81e01.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/e9c91cac-f3ef-4a66-b50d-8d133596efaf.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/6bae0166-fe6b-4ecd-8331-ab8a7c36ab07.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/64ed6954-fcc7-491e-b9e1-05b6ebf738ee.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/96a273a6-ce2a-40aa-a7af-691cd95723a9.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/184cb240-f1d9-4b73-96de-800d77f6aba4.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2550000/930a605f-9782-4038-8460-bee513e2b098.root
Queue
