universe = vanilla
Executable = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022EE/Job_test_1.sh
should_transfer_files = YES
Transfer_Input_Files = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022EE/Job_test_1.sh, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_vbf/bin/vbfhmm_config_run3_vbf_uncertainty_top_2022EE, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_vbf/libCROWNLIB.so
Proxy_path = /afs/cern.ch/user/j/jiahua/proxy/x509up_u139833
output_path = /eos/user/j/jiahua/MC_2022EE_inc/MC_2022EE_vbf/TbarWplusto2L2Nu_powheg_22EE_ext1-v2/eos/user/j/jiahua/MC_2022EE_inc/MC_2022EE_vbf/_UL
arguments = $(Proxy_path) $(output_path) $(input_name) $(ClusterID) $(ProcId)
Output = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022EE/Jobs/TbarWplusto2L2Nu_powheg_22EE_ext1-v2_$(ClusterId)_$(ProcId).out
Error = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022EE/Jobs/TbarWplusto2L2Nu_powheg_22EE_ext1-v2_$(ClusterId)_$(ProcId).err
Log = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022EE/Jobs/TbarWplusto2L2Nu_powheg_22EE_ext1-v2_$(ClusterId)_$(ProcId).log
request_cpus = 1
+JobFlavour = "workday"input_name = root://cms-xrd-global.cern.ch/2025/11/25 17:07:53 ERROR DAS QL ERROR, query=file dataset = instance = prod/global, idx=4, msg=unable to parse DAS query
Queue
input_name = root://cms-xrd-global.cern.ch/ERROR: das parser error: DAS QL ERROR, query=file dataset = instance = prod/global, idx=4, msg=unable to parse DAS query
Queue
