universe = vanilla
Executable = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022EE/Job_test_1.sh
should_transfer_files = YES
Transfer_Input_Files = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022EE/Job_test_1.sh, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_vbf/bin/vbfhmm_config_run3_vbf_HornVeto_top_2022EE, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_vbf/libCROWNLIB.so
Proxy_path = /afs/cern.ch/user/j/jiahua/proxy/x509up_u139833
output_path = /eos/user/j/jiahua/MC_2022EE_inc/MC_2022EE_vbf/TTH_Hto2Mu_M-125_powheg_22EE
arguments = $(Proxy_path) $(output_path) $(input_name) $(ClusterID) $(ProcId)
Output = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022EE/Jobs/TTH_Hto2Mu_M-125_powheg_22EE_$(ClusterId)_$(ProcId).out
Error = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022EE/Jobs/TTH_Hto2Mu_M-125_powheg_22EE_$(ClusterId)_$(ProcId).err
Log = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022EE/Jobs/TTH_Hto2Mu_M-125_powheg_22EE_$(ClusterId)_$(ProcId).log
request_cpus = 1
+JobFlavour = "workday"
input_name = root://cms-xrd-global.cern.ch/Python path configuration:
Queue
input_name = root://cms-xrd-global.cern.ch/  PYTHONHOME = '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt'
Queue
input_name = root://cms-xrd-global.cern.ch/  PYTHONPATH = (not set)
Queue
input_name = root://cms-xrd-global.cern.ch/  program name = '/usr/bin/python3'
Queue
input_name = root://cms-xrd-global.cern.ch/  isolated = 0
Queue
input_name = root://cms-xrd-global.cern.ch/  environment = 1
Queue
input_name = root://cms-xrd-global.cern.ch/  user site = 1
Queue
input_name = root://cms-xrd-global.cern.ch/  import site = 1
Queue
input_name = root://cms-xrd-global.cern.ch/  sys._base_executable = '/usr/bin/python3'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.base_prefix = '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.base_exec_prefix = '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.platlibdir = 'lib64'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.executable = '/usr/bin/python3'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.prefix = '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.exec_prefix = '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.path = [
Queue
input_name = root://cms-xrd-global.cern.ch/    '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt/lib64/python39.zip',
Queue
input_name = root://cms-xrd-global.cern.ch/    '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt/lib64/python3.9',
Queue
input_name = root://cms-xrd-global.cern.ch/    '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt/lib64/python3.9/lib-dynload',
Queue
input_name = root://cms-xrd-global.cern.ch/  ]
Queue
input_name = root://cms-xrd-global.cern.ch/Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Queue
input_name = root://cms-xrd-global.cern.ch/Python runtime state: core initialized
Queue
input_name = root://cms-xrd-global.cern.ch/ModuleNotFoundError: No module named 'encodings'
Queue
input_name = root://cms-xrd-global.cern.ch/
Queue
input_name = root://cms-xrd-global.cern.ch/Current thread 0x00007f7455218740 (most recent call first):
Queue
input_name = root://cms-xrd-global.cern.ch/<no Python frame>
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/TTH_Hto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/cef90b8d-5501-461e-bb34-2e7dfa17c8e5.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/TTH_Hto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2540000/b0b0c40c-fa2e-4dcf-95a9-25bee4acb4fe.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/TTH_Hto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2540000/39564a59-e6f6-4bdf-ac8b-4fd3efc48afa.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/TTH_Hto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2540000/bb7953d0-5cfa-4b54-9fef-967eeb298d71.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/TTH_Hto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/c3b3cdde-d349-4e1b-98ab-3ee49ea90c9b.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/TTH_Hto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/cb811ce1-2815-493a-ab5a-2a5f96820910.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/TTH_Hto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/38b81acd-8ac4-4889-8d24-20dc393d708d.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/TTH_Hto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/5c11304d-22fa-4b9e-8f96-f6789ff217eb.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/TTH_Hto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/8afb2121-acf2-4680-b4e0-784ffa421295.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/TTH_Hto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2540000/6607c6a8-6bc8-484b-9e39-018509397001.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/TTH_Hto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2540000/df2a564b-ac2d-4aec-ad1e-9a4e83b3d1cf.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/TTH_Hto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2540000/ea5334be-235f-4de5-a742-e830582b9b07.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/TTH_Hto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2540000/068d02ae-c05d-4dc5-8c1c-21e9581ebc23.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/TTH_Hto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2540000/859ac9a6-1f35-4335-8bdf-53ee177051cf.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/TTH_Hto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2540000/9e47a55f-a7e1-4b77-9bf7-d58779d75050.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/TTH_Hto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2540000/33dbba89-f0d4-4834-8bcd-9debbc51839d.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/TTH_Hto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2540000/f0e92cd0-0bf8-46ee-a5ca-5bf1fa5550a1.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/TTH_Hto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2540000/9766f27f-340f-4f1e-bc42-b311f7e6334b.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/TTH_Hto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/2540000/a772a792-6d34-4689-aef5-fcf3aca2f245.root
Queue
