universe = vanilla
Executable = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022EE/Job_test_1.sh
should_transfer_files = YES
Transfer_Input_Files = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022EE/Job_test_1.sh, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_2022EE/bin/vbfhmm_config_run3_vbf_HornVeto_top_2022EE, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_2022EE/libCROWNLIB.so
Proxy_path = /afs/cern.ch/user/j/jiahua/proxy/x509up_u139833
output_path = /eos/user/j/jiahua/MC_2022EE_inc/MC_2022EE_vbf/WminusH_Hto2Mu_WtoAll_M-125_powheg_22EE
arguments = $(Proxy_path) $(output_path) $(input_name) $(ClusterID) $(ProcId)
Output = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022EE/Jobs/WminusH_Hto2Mu_WtoAll_M-125_powheg_22EE_$(ClusterId)_$(ProcId).out
Error = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022EE/Jobs/WminusH_Hto2Mu_WtoAll_M-125_powheg_22EE_$(ClusterId)_$(ProcId).err
Log = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022EE/Jobs/WminusH_Hto2Mu_WtoAll_M-125_powheg_22EE_$(ClusterId)_$(ProcId).log
request_cpus = 1
+JobFlavour = "workday"
input_name = root://cms-xrd-global.cern.ch/Python path configuration:
Queue
input_name = root://cms-xrd-global.cern.ch/  PYTHONHOME = '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt'
Queue
input_name = root://cms-xrd-global.cern.ch/  PYTHONPATH = (not set)
Queue
input_name = root://cms-xrd-global.cern.ch/  program name = '/usr/bin/python3'
Queue
input_name = root://cms-xrd-global.cern.ch/  isolated = 0
Queue
input_name = root://cms-xrd-global.cern.ch/  environment = 1
Queue
input_name = root://cms-xrd-global.cern.ch/  user site = 1
Queue
input_name = root://cms-xrd-global.cern.ch/  import site = 1
Queue
input_name = root://cms-xrd-global.cern.ch/  sys._base_executable = '/usr/bin/python3'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.base_prefix = '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.base_exec_prefix = '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.platlibdir = 'lib64'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.executable = '/usr/bin/python3'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.prefix = '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.exec_prefix = '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.path = [
Queue
input_name = root://cms-xrd-global.cern.ch/    '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt/lib64/python39.zip',
Queue
input_name = root://cms-xrd-global.cern.ch/    '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt/lib64/python3.9',
Queue
input_name = root://cms-xrd-global.cern.ch/    '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt/lib64/python3.9/lib-dynload',
Queue
input_name = root://cms-xrd-global.cern.ch/  ]
Queue
input_name = root://cms-xrd-global.cern.ch/Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Queue
input_name = root://cms-xrd-global.cern.ch/Python runtime state: core initialized
Queue
input_name = root://cms-xrd-global.cern.ch/ModuleNotFoundError: No module named 'encodings'
Queue
input_name = root://cms-xrd-global.cern.ch/
Queue
input_name = root://cms-xrd-global.cern.ch/Current thread 0x00007f7ebd067740 (most recent call first):
Queue
input_name = root://cms-xrd-global.cern.ch/<no Python frame>
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WminusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/b95cc838-69da-49c7-8e43-e580c884fa75.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WminusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/269dd5ef-113a-4a0c-8d03-104aef54ffbc.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WminusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/1974b5d2-a1e3-474b-8dd8-6d7fd381a579.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WminusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/e34acca5-ed90-4105-b548-d113dbe107de.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WminusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/25af3906-01a9-4e87-a33f-283700e0d254.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WminusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/3ba758ad-dedd-49c5-912d-80601a769ddf.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WminusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/324e6a2b-3302-4aa1-b885-9e799ce19d9e.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WminusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/84bc4227-7c15-425f-9fa2-d77429de94bc.root
Queue
