universe = vanilla
Executable = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022EE/Job_test_1.sh
should_transfer_files = YES
Transfer_Input_Files = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022EE/Job_test_1.sh, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_vbf/bin/vbfhmm_config_run3_vbf_uncertainty_top_2022EE, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_vbf/libCROWNLIB.so
Proxy_path = /afs/cern.ch/user/j/jiahua/proxy/x509up_u139833
output_path = /eos/user/j/jiahua/MC_2022EE_inc/MC_2022EE_vbf/GluGluHto2Mu_M-125_powheg_22EE
arguments = $(Proxy_path) $(output_path) $(input_name) $(ClusterID) $(ProcId)
Output = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022EE/Jobs/GluGluHto2Mu_M-125_powheg_22EE_$(ClusterId)_$(ProcId).out
Error = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022EE/Jobs/GluGluHto2Mu_M-125_powheg_22EE_$(ClusterId)_$(ProcId).err
Log = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022EE/Jobs/GluGluHto2Mu_M-125_powheg_22EE_$(ClusterId)_$(ProcId).log
request_cpus = 1
+JobFlavour = "workday"
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v1/2550000/e9c1ef60-2c46-4933-a1b8-a082cb28074c.root
Queue
