universe = vanilla
Executable = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2023/Job_test_data.sh
should_transfer_files = YES
Transfer_Input_Files = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2023/Job_test_data.sh, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_vbf/bin/vbfhmm_config_run3_vbf_HornVeto_data_2023, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_vbf/libCROWNLIB.so
Proxy_path = /afs/cern.ch/user/j/jiahua/proxy/x509up_u139833
output_path = /eos/user/j/jiahua/MC_2023_inc/MC_2023_vbf/Muon0_UL23C-24Jan2024_v1-v1
arguments = $(Proxy_path) $(output_path) $(input_name) $(ClusterID) $(ProcId)
Output = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2023/Jobs/Muon0_UL23C-24Jan2024_v1-v1_$(ClusterId)_$(ProcId).out
Error = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2023/Jobs/Muon0_UL23C-24Jan2024_v1-v1_$(ClusterId)_$(ProcId).err
Log = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2023/Jobs/Muon0_UL23C-24Jan2024_v1-v1_$(ClusterId)_$(ProcId).log
request_cpus = 1
+JobFlavour = "workday"
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/f1c56c4b-828b-4c38-b396-ad1e96a850d8.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/e7240306-dad0-4b81-9ab5-a2c8f000b81d.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/2d5585d0-907d-40d6-9ee6-d9473b87c36f.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/bdc80e6b-8257-4018-8a2c-965375a6734b.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/63cf675b-ddd2-4845-9fab-1e037aa44fc5.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/af930772-1d3a-40cc-86b2-116cab7b50be.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/83d0d7a5-e275-4d00-8012-1714043f52dc.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/feca55df-6081-4557-8bdd-cdbe5d4703f1.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/dc7de4ed-4ae3-4679-b087-fb1fea4e4561.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/1b7d2e42-8874-47e9-94c9-e51ee04f0e5b.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/23d49dcb-826e-4d77-b0c8-ac6751dbbe3d.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/9e0c54c0-a692-4d27-94ec-2208a9b0149e.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/78ccc0c4-9d99-4ee2-b752-43d7db7bd55b.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/5a457dac-c4ef-48f9-bd8a-5d56c6896e8e.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/761b60b1-a701-4e10-b870-2bde9e217d5f.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/9e9413b1-2211-46ca-b82d-a35c3113be8b.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/f82ce494-97ac-4b2e-aba7-e1d6c864461b.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/3b5f8e0e-c88f-4b46-8fc7-652691c4696c.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/3b0d9e1e-c8ae-4a3a-92a4-13b56fb96c39.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/dad0d150-4cad-4528-9f15-e87ef2e08f59.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/56497b0d-afb9-4de3-b6ae-713119b56ffd.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/4f828ff3-cd32-4b81-902d-f9dd576ffdda.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/50d6da29-392a-4f60-a9a9-8964fca0cb6f.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/b9eb4e0f-bcd7-40e9-9740-4022612da60d.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/bf326799-25c1-4aae-8242-a23ea2d208cd.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/84e863fd-5ade-4143-a397-36c0efa29ebb.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/5e660635-e80d-4b03-8cd7-e1838887dbad.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/835fdda0-7b07-48e2-9403-4114f5882b2a.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/8eac96a1-8e4e-48c8-807e-bac1207cb6d8.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/2771ad4f-0653-418e-a374-5d2af279be7d.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/04325c0b-1e31-4c80-8deb-21791c077590.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/e0ed2414-51a7-43d1-b4a8-21f6040b7862.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/22d8c6e9-a4e7-4f03-85f7-3e4122864308.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/2820000/8dbd1bbb-edc9-4bfb-86ce-7204e86ff072.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v1-v1/28110000/c5b093c3-7a00-4ae6-a3c9-7f79c90ffb74.root
Queue
