universe = vanilla
Executable = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022EE/Job_test_1.sh
should_transfer_files = YES
Transfer_Input_Files = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022EE/Job_test_1.sh, /afs/cern.ch/user/j/jiahua/CROWN_run3/build/bin/vbfhmm_config_run3_Inc_v4_JetVeto_top_2022EE, /afs/cern.ch/user/j/jiahua/CROWN_run3/build/libCROWNLIB.so
Proxy_path = /afs/cern.ch/user/j/jiahua/proxy/x509up_u139833
output_path = /eos/user/j/jiahua/MC_2022EE_inc/WminusH_Hto2Mu_WtoAll_M-125_powheg_22EE
arguments = $(Proxy_path) $(output_path) $(input_name) $(ClusterID) $(ProcId)
Output = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022EE/Jobs/WminusH_Hto2Mu_WtoAll_M-125_powheg_22EE_$(ClusterId)_$(ProcId).out
Error = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022EE/Jobs/WminusH_Hto2Mu_WtoAll_M-125_powheg_22EE_$(ClusterId)_$(ProcId).err
Log = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022EE/Jobs/WminusH_Hto2Mu_WtoAll_M-125_powheg_22EE_$(ClusterId)_$(ProcId).log
request_cpus = 1
+JobFlavour = "workday"
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WminusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/b95cc838-69da-49c7-8e43-e580c884fa75.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WminusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/269dd5ef-113a-4a0c-8d03-104aef54ffbc.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WminusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/1974b5d2-a1e3-474b-8dd8-6d7fd381a579.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WminusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/e34acca5-ed90-4105-b548-d113dbe107de.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WminusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/25af3906-01a9-4e87-a33f-283700e0d254.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WminusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/3ba758ad-dedd-49c5-912d-80601a769ddf.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WminusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/324e6a2b-3302-4aa1-b885-9e799ce19d9e.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/WminusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/84bc4227-7c15-425f-9fa2-d77429de94bc.root
Queue
