universe = vanilla
Executable = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022EE/Job_test_1.sh
should_transfer_files = YES
Transfer_Input_Files = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022EE/Job_test_1.sh, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_2022/bin/vbfhmm_config_run3_vbf_test_top_2022EE, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_2022/libCROWNLIB.so
Proxy_path = /afs/cern.ch/user/j/jiahua/proxy/x509up_u139833
output_path = /eos/user/j/jiahua/MC_2022EE_inc/VBFHto2Mu_M-125_powheg_22EE
arguments = $(Proxy_path) $(output_path) $(input_name) $(ClusterID) $(ProcId)
Output = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022EE/Jobs/VBFHto2Mu_M-125_powheg_22EE_$(ClusterId)_$(ProcId).out
Error = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022EE/Jobs/VBFHto2Mu_M-125_powheg_22EE_$(ClusterId)_$(ProcId).err
Log = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022EE/Jobs/VBFHto2Mu_M-125_powheg_22EE_$(ClusterId)_$(ProcId).log
request_cpus = 1
+JobFlavour = "workday"
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/VBFHto2Mu_M-125_TuneCP5_withDipoleRecoil_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/400d66cf-4f82-4b91-bd14-058551fcbdf0.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/VBFHto2Mu_M-125_TuneCP5_withDipoleRecoil_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/7b0c0aa7-aa5d-4f6b-adac-cf076a1afe1d.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/VBFHto2Mu_M-125_TuneCP5_withDipoleRecoil_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/03865492-4a5d-4ec1-9c7b-fabd14c43d5e.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/VBFHto2Mu_M-125_TuneCP5_withDipoleRecoil_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/27149280-5995-46ce-8451-9542c3836d83.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/VBFHto2Mu_M-125_TuneCP5_withDipoleRecoil_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/e7b08496-f995-4280-a5de-ac8803c9dde1.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/VBFHto2Mu_M-125_TuneCP5_withDipoleRecoil_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/d3f4902d-9d5c-48a2-b9a5-b84b74b8201c.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/VBFHto2Mu_M-125_TuneCP5_withDipoleRecoil_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/b0540f69-dd7e-49ff-83d9-b6e1f3d80753.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/VBFHto2Mu_M-125_TuneCP5_withDipoleRecoil_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/08f2be07-aa16-42b1-8964-61d22ce5177d.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/VBFHto2Mu_M-125_TuneCP5_withDipoleRecoil_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/e67b03ea-e7f1-4e97-bc80-304e48e6ee08.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/VBFHto2Mu_M-125_TuneCP5_withDipoleRecoil_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/bc97c33a-5e3b-4585-9ccd-505223146ffa.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/VBFHto2Mu_M-125_TuneCP5_withDipoleRecoil_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/8e1dc822-7b6a-4666-ad04-b913cd17d88e.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22EENanoAODv12/VBFHto2Mu_M-125_TuneCP5_withDipoleRecoil_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v3/50000/55e0f227-2950-4f4a-9adc-87c357b4cff2.root
Queue
