universe = vanilla
Executable = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2023BPix/Job_test_data.sh
should_transfer_files = YES
Transfer_Input_Files = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2023BPix/Job_test_data.sh, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_2022/bin/vbfhmm_config_run3_vbf_test_data_2023BPix, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_2022/libCROWNLIB.so
Proxy_path = /afs/cern.ch/user/j/jiahua/proxy/x509up_u139833
output_path = /eos/user/j/jiahua/MC_2023BPix_inc/Muon0_Run2023D-24Jan2024_v1-v1
arguments = $(Proxy_path) $(output_path) $(input_name) $(ClusterID) $(ProcId)
Output = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2023BPix/Jobs/Muon0_Run2023D-24Jan2024_v1-v1_$(ClusterId)_$(ProcId).out
Error = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2023BPix/Jobs/Muon0_Run2023D-24Jan2024_v1-v1_$(ClusterId)_$(ProcId).err
Log = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2023BPix/Jobs/Muon0_Run2023D-24Jan2024_v1-v1_$(ClusterId)_$(ProcId).log
request_cpus = 1
+JobFlavour = "workday"
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/c79e7313-23f3-4a66-9c93-fd4a4b962b50.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/c0763a4b-4658-4b6b-8c90-4c1e8d0d8f45.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/477c33d7-646c-4e96-a927-322fe130d035.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/c48e1768-f4d6-4f54-9878-5231800dfbec.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/cb2bf241-38c1-44f2-a8fb-92002b16b1cd.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/9c88a26a-b2b1-4528-a90d-bfee89ba098b.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/724bf416-ff42-4a96-88cd-f88609d26e2a.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/b224fe0a-fe00-4bcc-a4c3-7b930435c945.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/870eb462-d07a-47ba-8fb3-8dce6f52d3ef.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/de84e7cc-535f-46a4-a54f-b8ca494f1b3b.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/19de9def-6be5-4052-8e82-7f05eeaae16d.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/47d01f1c-f35e-4f08-939d-b53bb6a34668.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/362331f4-ff50-4f7f-9e35-128cd3eceab3.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/f2a38912-5ef3-4c58-bb29-7ee307dcf117.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/96a6f2a8-e852-4650-8278-a9274e77cd2c.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/5c35e684-5721-4f82-a4b5-b9cae194b34d.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/e41cabad-a891-4f72-881d-dbb7b8460e3d.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/63ced625-7d0e-47d7-bb09-59d0e0303b07.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/57e85e2a-c944-478d-b840-7acf254f0286.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/a7ab4a13-d058-4a76-acf1-421ce8f98469.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/fb3386b8-ae6e-40b0-a891-a2cd0a2575e2.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/bb9e25d6-62b8-4256-a133-d9f518e5d42d.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/c72ac9c3-b3ea-4fb2-9057-9e0d990d2c95.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/322868d8-a167-42ec-a1b4-7a629989a946.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/763635d3-f850-428b-988e-6615d096bfe0.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/4107a60e-d80b-4bc0-9922-f27fea380522.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/857f838f-82d6-4133-b5c4-b9a97fa21683.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/e47b0b7f-f373-4169-a05a-143eff0bf433.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/80ae9303-a75d-43b0-b59d-e69c4e832c06.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/e841a5d6-4847-49d7-9b5c-88e9eb7d7f82.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/09dc4ba3-1c96-446f-b5d2-5023bcea005e.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/148d06d4-fb35-4215-a061-fbfddab1715d.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/5afbc010-9f1b-43d6-bd47-644597d925f4.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/18adad0a-9477-4428-a968-01c9eeb8c2d3.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/084077c3-a16e-40ec-94fb-fe25f752b6d8.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/575ae5da-326e-40e8-aa0f-d0bfa8c8e6b9.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/326b6264-68c8-4604-bdbd-f115d099be3d.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/6f19928c-7f47-44e5-abb5-900b94896cb9.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/480ed15d-70b7-4f4e-97b1-d75bcab1beea.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/6a544231-5026-42c1-93dd-c53cb200e6f9.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/73499aad-3135-42ad-9537-0825a15ab936.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/46d0d0d3-38a2-42e0-8eaf-b4787c4ab56d.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/f3bb40c2-95a6-4e1f-98a3-dde4d1f605cb.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/909b0e06-9654-4df7-a539-3125017d2731.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/b6c0f7f5-72ce-4dac-9126-6f1b8f52b691.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/5be74e0d-2be4-42f6-a886-1362178f8113.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/7847cc39-edd2-4de8-aaa1-fc40f0bba330.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/0c4e32f2-dbb1-4630-a605-ed13902f3548.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/4f8b31c0-40c1-4b59-96bb-0a610d298347.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/1c2cce0b-c7e5-4b17-a294-4e62116ffbf9.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/72119a19-f857-445e-beff-8aa8142c8d3c.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/f1b1904c-c700-4a80-9b39-c77500acaabc.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/3b014334-46be-4cd8-9b6c-f2f3a8c3e90d.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/8de85d4d-dece-47a4-a529-2cb01e659523.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/3d0d9f41-8632-4501-a51b-82616fd13f0c.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/429d17f0-dabb-4cfc-9fc0-172ce2680971.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/41cccf06-47b2-4bc0-b458-4a1a95eb4369.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/3b08dc7e-ace0-4962-9b7d-fcda74c41a85.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/30000/22fcd46f-af2a-4c9e-ad3e-bdb8eea52968.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/2810000/03ea9cda-e5db-4539-8512-f7132e80d525.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023D/Muon0/NANOAOD/24Jan2024_v1-v1/2810000/e6523322-3609-45cf-8793-2a708c651d2c.root
Queue
