universe = vanilla
Executable = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022/Job_test_data.sh
should_transfer_files = YES
Transfer_Input_Files = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022/Job_test_data.sh, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_2022/bin/vbfhmm_config_run3_Inc_v4_JetVeto_data_2022, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_2022/libCROWNLIB.so
Proxy_path = /afs/cern.ch/user/j/jiahua/proxy/x509up_u139833
output_path = /eos/user/j/jiahua/MC_2022_inc/MC_2022_VBF/WZto3LNu_powheg_22
arguments = $(Proxy_path) $(output_path) $(input_name) $(ClusterID) $(ProcId)
Output = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022/Jobs/WZto3LNu_powheg_22_resub1_$(ClusterId)_$(ProcId).out
Error = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022/Jobs/WZto3LNu_powheg_22_resub1_$(ClusterId)_$(ProcId).err
Log = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022/Jobs/WZto3LNu_powheg_22_resub1_$(ClusterId)_$(ProcId).log
request_cpus = 1
+JobFlavour = "workday"
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WZto3LNu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/2520000/3b58b311-a25a-4d3c-8610-30cfc64f21a8.root 
Queue
