universe = vanilla
Executable = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022/Job_test_1.sh
should_transfer_files = YES
Transfer_Input_Files = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022/Job_test_1.sh, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_vbf/bin/vbfhmm_config_run3_vbf_uncertainty_top_2022, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_vbf/libCROWNLIB.so
Proxy_path = /afs/cern.ch/user/j/jiahua/proxy/x509up_u139833
output_path = /eos/user/j/jiahua/MC_2022_inc/MC_2022_VBF/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7_22
arguments = $(Proxy_path) $(output_path) $(input_name) $(ClusterID) $(ProcId)
Output = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022/Jobs/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7_22_$(ClusterId)_$(ProcId).out
Error = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022/Jobs/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7_22_$(ClusterId)_$(ProcId).err
Log = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_vbf_2022/Jobs/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7_22_$(ClusterId)_$(ProcId).log
request_cpus = 1
+JobFlavour = "workday"
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/96bd3668-e763-4f60-8735-14020eacff7e.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/a92c12d5-426e-4616-baa8-53322668d0fe.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/781071ac-8bde-41d9-a5f8-de9e5fbddc62.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/5cefbf92-e1ea-4902-adbc-6719f2d1284f.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/650e6bb5-e323-46ec-b276-fb24050fae5e.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/4d1d2beb-c558-4256-8bb6-87dce2e94b24.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/c62034bb-a977-4a1c-9da5-15e69da94f9c.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/f7ad2334-785b-4377-bbf9-136725a1892f.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/259efc38-4a4b-49eb-b716-f4da2b97c12b.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/6be515cb-9278-4757-b6dd-c3042bfb5328.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/215f812b-c681-4ed2-ab80-22fdc39d619e.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/553dbef8-7fdb-4672-81f9-217854ca2486.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/5a6e5cd8-ca8e-473b-92a4-de207a2749ba.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/279484e7-430c-4cec-b8b2-44e7e82f657a.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/0ff352ef-52fa-4ed9-bd0c-c141af0f15dc.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/cc17b553-b1f0-4c6b-ba29-30e86fac1c93.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/39344b1d-6a5e-40c6-b039-a10ff968541e.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/ddbbf1c9-3ddd-4e13-a9c3-18c8113fe831.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/3e461e77-ae0c-4668-bfcf-ceac8f17478b.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/c3f201e6-3f24-47e7-afd1-5ca4c0efb71f.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/1e36bfa5-ccb4-4204-baa7-4d78e786796e.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/eb914089-bf4c-49f0-b885-9e2587eb06f5.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/90e60f83-5f41-476a-bc87-9baa19284ecc.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/6b19485d-8908-4517-97c4-91140329ff63.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/f669b603-540f-4b9e-a509-328e18fcac45.root
Queue
