universe = vanilla
Executable = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor/Job_test_data.sh
should_transfer_files = YES
Transfer_Input_Files = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor/Job_test_data.sh, /afs/cern.ch/user/j/jiahua/CROWN_run3/build/bin/vbfhmm_config_run3_Inc_v4_JetVeto_data_2023, /afs/cern.ch/user/j/jiahua/CROWN_run3/build/libCROWNLIB.so
Proxy_path = /afs/cern.ch/user/j/jiahua/proxy/x509up_u139833
output_path = /eos/user/j/jiahua/MC_2023_inc/_
arguments = $(Proxy_path) $(output_path) $(input_name) $(ClusterID) $(ProcId)
Output = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor/Jobs/__$(ClusterId)_$(ProcId).out
Error = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor/Jobs/__$(ClusterId)_$(ProcId).err
Log = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor/Jobs/__$(ClusterId)_$(ProcId).log
request_cpus = 1
+JobFlavour = "workday"
input_name = root://cms-xrd-global.cern.ch/2025/08/22 10:18:31 ERROR DAS QL ERROR, query=file dataset = instance = prod/global, idx=4, msg=unable to parse DAS query
Queue
input_name = root://cms-xrd-global.cern.ch/ERROR: das parser error: DAS QL ERROR, query=file dataset = instance = prod/global, idx=4, msg=unable to parse DAS query
Queue
