universe = vanilla
Executable = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor/Job_test_data.sh
should_transfer_files = YES
Transfer_Input_Files = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor/Job_test_data.sh, /afs/cern.ch/user/j/jiahua/CROWN_run3/build/bin/vbfhmm_config_run3_Inc_v4_JetVeto_data_2023, /afs/cern.ch/user/j/jiahua/CROWN_run3/build/libCROWNLIB.so
Proxy_path = /afs/cern.ch/user/j/jiahua/proxy/x509up_u139833
output_path = /eos/user/j/jiahua/MC_2023_inc/Muon0_Run2023C-24Jan2024_v3-v1
arguments = $(Proxy_path) $(output_path) $(input_name) $(ClusterID) $(ProcId)
Output = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor/Jobs/Muon0_Run2023C-24Jan2024_v3-v1_$(ClusterId)_$(ProcId).out
Error = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor/Jobs/Muon0_Run2023C-24Jan2024_v3-v1_$(ClusterId)_$(ProcId).err
Log = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor/Jobs/Muon0_Run2023C-24Jan2024_v3-v1_$(ClusterId)_$(ProcId).log
request_cpus = 1
+JobFlavour = "workday"
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v3-v1/2810000/a886ffcb-4411-4da9-be97-231e5440074f.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v3-v1/2810000/0975a49a-9b49-4e47-b872-56aa3d0d206f.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v3-v1/2810000/d67d5c42-99f0-48f2-b206-4e4bc92ee75f.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v3-v1/2810000/6b676642-0736-4be1-ac80-0e114a2d19a6.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v3-v1/2810000/35353f2f-030c-464d-8a32-18447e5f6f25.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v3-v1/2810000/7d3e154c-efd9-4566-a3c5-a1359a96878f.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v3-v1/2810000/c0e8b9d5-3bd2-46c3-8f75-9d62a196a72d.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v3-v1/2810000/3c43faaf-5803-4657-9284-7f51b85360e1.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v3-v1/2810000/1ae9d478-7b2c-4533-adb5-f601adf28ff9.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v3-v1/2810000/53a6f7e9-c4b0-4882-ae2a-31eac57d096f.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v3-v1/2810000/10266442-c2d9-4fbe-95ed-9a72e9fb05bb.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v3-v1/2810000/e1926cc4-51d4-4f75-b42e-7658ea96149c.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v3-v1/2810000/6043cdcb-6bb4-4247-87a0-1b8e6c93d648.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v3-v1/2810000/50f72ac3-5715-4fe1-bc2b-40af237cee93.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v3-v1/2810000/1cfc5478-68b2-4c54-8404-e93bd5cf766f.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/data/Run2023C/Muon0/NANOAOD/24Jan2024_v3-v1/2810000/fd318377-99db-446c-b67f-6d0588ee6d17.root
Queue
