universe = vanilla
Executable = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor/Job_test_data.sh
should_transfer_files = YES
Transfer_Input_Files = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor/Job_test_data.sh, /afs/cern.ch/user/j/jiahua/CROWN_run3/build/bin/vbfhmm_config_run3_Inc_v4_JetVeto_data_2023, /afs/cern.ch/user/j/jiahua/CROWN_run3/build/libCROWNLIB.so
Proxy_path = /afs/cern.ch/user/j/jiahua/proxy/x509up_u139833
output_path = /eos/user/j/jiahua/MC_2023_inc/TbarWplusto2L2Nu_powheg_23
arguments = $(Proxy_path) $(output_path) $(input_name) $(ClusterID) $(ProcId)
Output = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor/Jobs/TbarWplusto2L2Nu_powheg_23_resub1_$(ClusterId)_$(ProcId).out
Error = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor/Jobs/TbarWplusto2L2Nu_powheg_23_resub1_$(ClusterId)_$(ProcId).err
Log = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor/Jobs/TbarWplusto2L2Nu_powheg_23_resub1_$(ClusterId)_$(ProcId).log
request_cpus = 1
+JobFlavour = "workday"
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer23NanoAODv12/TbarWplusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2023_realistic_v15-v4/50000/08f88f59-f62b-48d8-a424-87dc7ef39489.root 
Queue
