import numpy as np

output = {}
branches = {"run": np.int64,
            "event": np.int64,
            "lumi": np.int64,
            "nmuons": int,
            "nelectrons": int,
            "nleptons": int,
            "nbjets_loose": int,
            "nbjets_medium": int,
            "njets": int,
            "met_pt": float,
            "met_phi": float,
            "mu1_fromH_pt": float,
            "mu1_fromH_eta": float,
            "mu1_fromH_phi": float,
            "mu2_fromH_pt": float,
            "mu2_fromH_eta": float,
            "mu2_fromH_phi": float,
            "H_pt": float,
            "H_eta": float,
            "H_phi": float,
            "H_mass": float,
            "BSC_pt_1": float,
            "BSC_pt_2": float,
            #"BSC_pt_rc_1": float,
            #"BSC_pt_rc_2": float,
            ##"BSC_pt_kit_1": float,
            ##"BSC_pt_kit_2": float,
            "BSC_ptErr_1": float,
            "BSC_ptErr_2": float,
            "jet1_pt": float,
            "jet1_eta": float,
            "jet1_phi": float,
            "jet1_mass": float,
            "jet2_pt": float,
            "jet2_eta": float,
            "jet2_phi": float,
            "jet2_mass": float,
            "dijet_mass": float,
            "dijet_eta": float,
            "dijet_pt": float,
            "dijet_phi": float,
            "mumuH_dR": float,
            "mu1_mu2_dphi": float,
            "mu1_fromH_ptErr": float,
            "mu2_fromH_ptErr": float,
            #"pt_rc_1": float,
            #"pt_rc_2": float,
            ##"pt_kit_1": float,
            ##"pt_kit_2": float,
            "y_star": float,
            "z_star": float,
            "R_pT": float,
            "diMu-mass_resolution": float,
            "diMu-mass_resolution_BSC": float,
            #"diMu_pt_rc": float,
            #"diMu_eta_rc": float,
            #"diMu_phi_rc": float,
            #"diMu_mass_rc": float,
            ##"diMu_pt_kit": float,
            ##"diMu_eta_kit": float,
            ##"diMu_phi_kit": float,
            ##"diMu_mass_kit": float,
            "diMufsr_pt": float,
            "diMufsr_eta": float,
            "diMufsr_phi": float,
            "diMufsr_mass": float,
            #"diMufsr_rc_pt": float,
            #"diMufsr_rc_eta": float,
            #"diMufsr_rc_phi": float,
            #"diMufsr_rc_mass": float,
            #"diMufsr_rc_BSC_pt": float,
            #"diMufsr_rc_BSC_eta": float,
            #"diMufsr_rc_BSC_phi": float,
            #"diMufsr_rc_BSC_mass": float,
            ##"diMufsr_kit_pt": float,
            ##"diMufsr_kit_eta": float,
            ##"diMufsr_kit_phi": float,
            ##"diMufsr_kit_mass": float,
            "diMufsr_kit_BSC_pt": float,
            "diMufsr_kit_BSC_eta": float,
            "diMufsr_kit_BSC_phi": float,
            "diMufsr_kit_BSC_mass": float,
            "diMufsr_BSC_pt": float,
            "diMufsr_BSC_eta": float,
            "diMufsr_BSC_phi": float,
            "diMufsr_BSC_mass": float,
            "weight": float,
            #"puweight": float,
            "eventWeight": float,
            "trg_single_mu24": bool,
            #"genWeight": float,
            #"puWeight": float,
            "SoftActivityJetNjets5": int,
            #"jet1_qgl": float,
            #"jet2_qgl": float,
            "diMu-mass_resolution_abs": float,
            "diMu-mass_resolution_BSC_abs": float,
            "log_dijet_mass": float,
            #"log_diMufsr_kit_pt": float,
            "log_diMufsr_kit_BSC_pt": float,
            "min_delta_eta_dimu_jets": float,
            "delta_eta_jj": float,
            "delta_phi_jj": float,
            "phi_CS": float,
            "cos_theta_CS": float,
            "pTMu1oMmm": float,
            "pTMu2oMmm": float,
            "delta_eta_dimu_jet1": float,
            "delta_phi_dimu_jet1": float,
            "min_delta_phi_dimu_jets": float,
            "1oDiMuResolution": float,
            "1oDiMuResolution_BSC": float,
            "TTH": bool,
            "VH": bool,
            "VBF": bool,
            "GGH": bool,
            "cate_index": int,
            "PDF_uncertainty_down": float,
            "PDF_uncertainty_up": float,
            "qcd_unc_down": float,
            "qcd_unc_up": float,
            "iso_MuonEffup": float,
            "iso_MuonEffdown": float,
            "id_MuonEffup": float,
            "id_MuonEffdown": float,
            "source_year": int,
            #"Mu1_fsr_rc_BSC_pt": float,
            #"Mu2_fsr_rc_BSC_pt": float,
            "Mu1_fsr_kit_BSC_pt": float,
            "Mu2_fsr_kit_BSC_pt": float,
            "Mu1_fsr_BSC_pt": float,
            "Mu2_fsr_BSC_pt": float,
            "Mu1_fsr_pt": float,
            "Mu2_fsr_pt": float,
}


#rm_sys=["diMu-mass_resolution_old","diMu-mass_resolution_abs_old", "diMu-mass_resolution_BSC_old", "diMu-mass_resolution_BSC_abs_old", "1oDiMuResolution_old", "1oDiMuResolution_BSC_old", "id_MuonEffup", "id_MuonEffdown", "iso_MuonEffup", "iso_MuonEffdown", "PDF_uncertainty_down", "PDF_uncertainty_up", "qcd_unc_down", "qcd_unc_up", "GGH","VBF","VH","TTH","trg_single_mu24"]
#for v in rm_sys:
#    branches.pop(v, None)   # remove if present, ignore if missing
#print(branches)

#for branch in branches:
#    output[branch] = np.array([])
#    #output[branch] = []

