universe = vanilla
Executable = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022/Job_test_1.sh
should_transfer_files = YES
Transfer_Input_Files = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022/Job_test_1.sh, /afs/cern.ch/user/j/jiahua/CROWN_run3/build/bin/vbfhmm_config_run3_Inc_v4_JetVeto_top_2022, /afs/cern.ch/user/j/jiahua/CROWN_run3/build/libCROWNLIB.so
Proxy_path = /afs/cern.ch/user/j/jiahua/proxy/x509up_u139833
output_path = /eos/user/j/jiahua/MC_2022_inc/WplusH_Hto2Mu_WtoAll_M-125_powheg_22
arguments = $(Proxy_path) $(output_path) $(input_name) $(ClusterID) $(ProcId)
Output = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022/Jobs/WplusH_Hto2Mu_WtoAll_M-125_powheg_22_$(ClusterId)_$(ProcId).out
Error = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022/Jobs/WplusH_Hto2Mu_WtoAll_M-125_powheg_22_$(ClusterId)_$(ProcId).err
Log = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022/Jobs/WplusH_Hto2Mu_WtoAll_M-125_powheg_22_$(ClusterId)_$(ProcId).log
request_cpus = 1
+JobFlavour = "workday"
input_name = root://cms-xrd-global.cern.ch/Python path configuration:
Queue
input_name = root://cms-xrd-global.cern.ch/  PYTHONHOME = '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt'
Queue
input_name = root://cms-xrd-global.cern.ch/  PYTHONPATH = (not set)
Queue
input_name = root://cms-xrd-global.cern.ch/  program name = '/usr/bin/python3'
Queue
input_name = root://cms-xrd-global.cern.ch/  isolated = 0
Queue
input_name = root://cms-xrd-global.cern.ch/  environment = 1
Queue
input_name = root://cms-xrd-global.cern.ch/  user site = 1
Queue
input_name = root://cms-xrd-global.cern.ch/  import site = 1
Queue
input_name = root://cms-xrd-global.cern.ch/  sys._base_executable = '/usr/bin/python3'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.base_prefix = '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.base_exec_prefix = '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.platlibdir = 'lib64'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.executable = '/usr/bin/python3'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.prefix = '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.exec_prefix = '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.path = [
Queue
input_name = root://cms-xrd-global.cern.ch/    '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt/lib64/python39.zip',
Queue
input_name = root://cms-xrd-global.cern.ch/    '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt/lib64/python3.9',
Queue
input_name = root://cms-xrd-global.cern.ch/    '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt/lib64/python3.9/lib-dynload',
Queue
input_name = root://cms-xrd-global.cern.ch/  ]
Queue
input_name = root://cms-xrd-global.cern.ch/Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Queue
input_name = root://cms-xrd-global.cern.ch/Python runtime state: core initialized
Queue
input_name = root://cms-xrd-global.cern.ch/ModuleNotFoundError: No module named 'encodings'
Queue
input_name = root://cms-xrd-global.cern.ch/
Queue
input_name = root://cms-xrd-global.cern.ch/Current thread 0x00007f6edb257740 (most recent call first):
Queue
input_name = root://cms-xrd-global.cern.ch/<no Python frame>
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/2540000/c178bd25-08d9-43d0-9085-ded5db5ef0c5.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/2540000/c691ad1b-9da7-483a-936e-1c5264812064.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/2540000/10c48b8e-509b-4de6-9b24-7ada179e4b67.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/2540000/bcee017d-cadc-4e2d-b180-ebcaea0d4a27.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/2540000/e1dbd460-7034-4602-8e46-76caf4a98544.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/2540000/a8d948ec-2939-4d67-b9c7-d51489c7832d.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/2540000/70af48a1-d0b6-4eaa-a7d8-6a65764e8119.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/2540000/5a486350-49e6-43e4-834a-94241a27068e.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/2540000/f62c50cd-6ead-44e0-bf1e-af0c18473c41.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/2540000/b7877c61-1d2f-4259-81e9-19a484c00ded.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/2540000/7488950f-caaa-43a7-ba0b-c2420a60bef9.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/2540000/4d728ef8-2280-4204-99d9-3e5b3aed63e9.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/2540000/1451cf73-7231-4e1e-8273-20b54fdf0a9b.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/2540000/4c035647-2b9b-488f-981a-771b64822faa.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/2540000/e6eb7784-8b49-43af-8c72-47a50011d4b9.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/2540000/4fc174df-0139-483d-9ceb-fd4c9260c027.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/2540000/64977bf8-083d-49e8-8c85-5c5cd2c951c2.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/2540000/227d4268-622e-4f25-a5ca-0c62f23de4aa.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/2540000/8b476a35-6b16-4b7e-97a8-76c8892fdc09.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/2540000/79e633a8-6177-4ad4-a782-0f69902a5026.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/2540000/efa53786-4224-478f-b6bd-f526ead369ff.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/2540000/2d773906-d4a5-4485-a15f-6c744826c0fa.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/2540000/71508b16-6d9b-4218-bcfe-3a3f485282bd.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/2540000/0ddd2354-a073-4dee-8f6a-514b2f7b6cd2.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/2540000/b25876f0-d59c-4ede-8057-cb913b2c2c2a.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WplusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/2540000/81eb4229-46dc-4cbe-b988-4d41bd54e15a.root
Queue
