universe = vanilla
Executable = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022/Job_test_1.sh
should_transfer_files = YES
Transfer_Input_Files = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022/Job_test_1.sh, /afs/cern.ch/user/j/jiahua/CROWN_run3/build/bin/vbfhmm_config_run3_Inc_v4_JetVeto_top_2022, /afs/cern.ch/user/j/jiahua/CROWN_run3/build/libCROWNLIB.so
Proxy_path = /afs/cern.ch/user/j/jiahua/proxy/x509up_u139833
output_path = /eos/user/j/jiahua/MC_2022_inc/WminusH_Hto2Mu_WtoAll_M-125_powheg_22
arguments = $(Proxy_path) $(output_path) $(input_name) $(ClusterID) $(ProcId)
Output = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022/Jobs/WminusH_Hto2Mu_WtoAll_M-125_powheg_22_$(ClusterId)_$(ProcId).out
Error = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022/Jobs/WminusH_Hto2Mu_WtoAll_M-125_powheg_22_$(ClusterId)_$(ProcId).err
Log = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022/Jobs/WminusH_Hto2Mu_WtoAll_M-125_powheg_22_$(ClusterId)_$(ProcId).log
request_cpus = 1
+JobFlavour = "workday"
input_name = root://cms-xrd-global.cern.ch/Python path configuration:
Queue
input_name = root://cms-xrd-global.cern.ch/  PYTHONHOME = '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt'
Queue
input_name = root://cms-xrd-global.cern.ch/  PYTHONPATH = (not set)
Queue
input_name = root://cms-xrd-global.cern.ch/  program name = '/usr/bin/python3'
Queue
input_name = root://cms-xrd-global.cern.ch/  isolated = 0
Queue
input_name = root://cms-xrd-global.cern.ch/  environment = 1
Queue
input_name = root://cms-xrd-global.cern.ch/  user site = 1
Queue
input_name = root://cms-xrd-global.cern.ch/  import site = 1
Queue
input_name = root://cms-xrd-global.cern.ch/  sys._base_executable = '/usr/bin/python3'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.base_prefix = '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.base_exec_prefix = '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.platlibdir = 'lib64'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.executable = '/usr/bin/python3'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.prefix = '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.exec_prefix = '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt'
Queue
input_name = root://cms-xrd-global.cern.ch/  sys.path = [
Queue
input_name = root://cms-xrd-global.cern.ch/    '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt/lib64/python39.zip',
Queue
input_name = root://cms-xrd-global.cern.ch/    '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt/lib64/python3.9',
Queue
input_name = root://cms-xrd-global.cern.ch/    '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-el9-gcc11-opt/lib64/python3.9/lib-dynload',
Queue
input_name = root://cms-xrd-global.cern.ch/  ]
Queue
input_name = root://cms-xrd-global.cern.ch/Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Queue
input_name = root://cms-xrd-global.cern.ch/Python runtime state: core initialized
Queue
input_name = root://cms-xrd-global.cern.ch/ModuleNotFoundError: No module named 'encodings'
Queue
input_name = root://cms-xrd-global.cern.ch/
Queue
input_name = root://cms-xrd-global.cern.ch/Current thread 0x00007fcd7d44e740 (most recent call first):
Queue
input_name = root://cms-xrd-global.cern.ch/<no Python frame>
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WminusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/50000/a3544aca-9a7b-4d7f-a007-648eebc7f7e4.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WminusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/50000/0478e5de-8abb-400b-befe-5aeb77682db3.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WminusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/50000/622d6017-1c76-4eba-aed8-82cbdb5edd97.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WminusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/50000/133d93a5-e735-44d8-873a-0733c39408f6.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/WminusH_Hto2Mu_WtoAll_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/50000/0fb3bb30-0ce2-479a-8a80-6fb14216191f.root
Queue
