universe = vanilla
Executable = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022/Job_test_1.sh
should_transfer_files = YES
Transfer_Input_Files = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022/Job_test_1.sh, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_2022/bin/vbfhmm_config_run3_vbf_test_top_2022, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_2022/libCROWNLIB.so
Proxy_path = /afs/cern.ch/user/j/jiahua/proxy/x509up_u139833
output_path = /eos/user/j/jiahua/MC_2022_inc/GluGluHto2Mu_M-125_powheg_22
arguments = $(Proxy_path) $(output_path) $(input_name) $(ClusterID) $(ProcId)
Output = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022/Jobs/GluGluHto2Mu_M-125_powheg_22_$(ClusterId)_$(ProcId).out
Error = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022/Jobs/GluGluHto2Mu_M-125_powheg_22_$(ClusterId)_$(ProcId).err
Log = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022/Jobs/GluGluHto2Mu_M-125_powheg_22_$(ClusterId)_$(ProcId).log
request_cpus = 1
+JobFlavour = "workday"
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/50000/154d3c87-08bf-4277-ba6f-d798a21fa339.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/50000/317887a3-18e7-4670-9685-66a15279fe02.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/50000/e3a0b34f-7f23-4bb0-b0c1-45028cd760ca.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/50000/3b811747-4bbc-48f2-aff0-660ef149ee41.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/50000/8a94ce36-c98c-43e4-a857-1b2c4cdae444.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/50000/f5f23b40-7769-49c3-81ad-3fc659398887.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/50000/a4ff3abe-a3e9-4bf3-bb44-e71593cf0078.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/50000/b070a6a9-442e-461e-8eca-e9f9662410b0.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/50000/b407fd94-e0ec-4902-b727-f49fe673fcae.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/50000/37941255-e6c1-4772-b918-3b3e17672616.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/50000/50a8a222-6823-40f2-820a-0c8652792a40.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/50000/8fda3937-5dee-4615-ad30-5a91eede2428.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/50000/e41796d6-345b-4000-852c-f132f2da51f0.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/50000/3d00e4d6-cd54-4b7f-8689-87a8193e5783.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/50000/74728346-9a33-4e77-9b56-c9a447388d54.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/50000/50a6cddf-f50d-41a3-bba8-01b0101ee119.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/50000/dc536472-9ae3-4536-8c50-f6744b31f74a.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/50000/a298b85f-5f27-4464-afa9-dfef8134fb5b.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/50000/6b752bbb-627a-4448-8126-1c7dafaacd27.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/50000/621a7972-5e05-44dc-8778-c1df01bc7644.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/GluGluHto2Mu_M-125_TuneCP5_13p6TeV_powheg-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v3/50000/c6e42bfc-d802-4db9-864f-b83f34a37b82.root
Queue
