universe = vanilla
Executable = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022/Job_test_1.sh
should_transfer_files = YES
Transfer_Input_Files = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022/Job_test_1.sh, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_2022/bin/vbfhmm_config_run3_vbf_test_top_2022, /afs/cern.ch/user/j/jiahua/CROWN_run3/build_2022/libCROWNLIB.so
Proxy_path = /afs/cern.ch/user/j/jiahua/proxy/x509up_u139833
output_path = /eos/user/j/jiahua/MC_2022_inc/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7_22
arguments = $(Proxy_path) $(output_path) $(input_name) $(ClusterID) $(ProcId)
Output = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022/Jobs/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7_22_$(ClusterId)_$(ProcId).out
Error = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022/Jobs/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7_22_$(ClusterId)_$(ProcId).err
Log = /afs/cern.ch/user/j/jiahua/CROWN_run3/condor_2022/Jobs/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7_22_$(ClusterId)_$(ProcId).log
request_cpus = 1
+JobFlavour = "workday"
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/96bd3668-e763-4f60-8735-14020eacff7e.root 
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/5a6e5cd8-ca8e-473b-92a4-de207a2749ba.root 
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/39344b1d-6a5e-40c6-b039-a10ff968541e.root 
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/ddbbf1c9-3ddd-4e13-a9c3-18c8113fe831.root 
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/3e461e77-ae0c-4668-bfcf-ceac8f17478b.root 
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/5cefbf92-e1ea-4902-adbc-6719f2d1284f.root 
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/39344b1d-6a5e-40c6-b039-a10ff968541e.root 
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/Run3Summer22NanoAODv12/EWK_2L2J_TuneCH3_13p6TeV_madgraph-herwig7/NANOAODSIM/130X_mcRun3_2022_realistic_v5-v2/130000/39344b1d-6a5e-40c6-b039-a10ff968541e.root 
Queue
