condor_submit Job_DYto2L-2Jets_MLL-50_amcatnloFXFX_23BPix.sub
condor_submit Job_GluGluHto2Mu_M-125_powheg_23BPix.sub
condor_submit Job_TTH_Hto2Mu_M-125_powheg_23BPix.sub
condor_submit Job_VBFHto2Mu_M-125_powheg_23BPix.sub
condor_submit Job_WminusH_Hto2Mu_WtoAll_M-125_powheg-minlo_23BPix.sub
condor_submit Job_WplusH_Hto2Mu_WtoAll_M-125_powheg-minlo_23BPix.sub
condor_submit Job_ZH_Hto2Mu_ZtoAll_M-125_powheg-minlo_23BPix.sub
condor_submit Job_TTto2L2Nu_powheg_23BPix.sub
condor_submit Job_WWto2L2Nu_powheg_23BPix.sub
condor_submit Job_WZto3LNu_powheg_23BPix_ext1-v2.sub
condor_submit Job_ZZto2L2Nu_powheg_23BPix.sub
condor_submit Job_ZZto4L_powheg_23BPix.sub
condor_submit Job_WZto2L2Q_powheg_23BPix.sub
condor_submit Job_ZZto2L2Q_powheg_23BPix.sub
condor_submit Job_TWminusto2L2Nu_powheg_23BPix.sub
condor_submit Job_TbarWplusto2L2Nu_powheg_23BPix.sub
condor_submit Job_DYto2Mu-2Jets_MLL-105To160_amcatnloFXFX_23BPix.sub

